version: "3.8"

services:
  api:
    image: tasksistem-api
    build:
      context: ./TaskSistem
      dockerfile: Dockerfile
    ports:
      - "5000:8080" # Porta para bater na API pelo Postman
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

      # 1. Substitui a Connection String do appsettings.json
      - ConnectionStrings__DataBase=Server=db;Database=TaskSistemDB;User Id=sa;Password=SuaSenhaForte123!;TrustServerCertificate=True;

      # 2. A CHAVE QUE EU TINHA ESQUECIDO (Substitui o JwtSettings:Secret):
      - JwtSettings__Secret=94ecd630-f9ff-49bf-bdec-59d05d18892a

    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuaSenhaForte123!
